# Generated by Django 4.0.5 on 2022-07-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_rename_name_accessrecord_webpage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='webpage_name',
            new_name='webpage',
        ),
    ]
